### ISSUE TITLE
달력 자세히 보기 UI 깨짐

### ISSUE THREAD

**Issue by Noverish** [mash-up-kr/Checkmate-ios#11]
<img width="402" alt="2018-09-10 5 38 02" src="https://user-images.githubusercontent.com/19399211/45286278-5a197980-b520-11e8-8028-5f00126f17f7.png">

**Comment by kor-Chipmunk** [comment]
- [x] 기타수당 컬렉션뷰 Width 문제 해결. 내역 확인하기 우측 버튼 이미지 새로 고침 - https://github.com/mash-up-kr/Checkmate-ios/commit/57b2a6a9923bdf3a377c88d493aefde33e6600b3
- [x] iPhone 8, 8 Plus, X 정상작동 확인함

<img width="336" alt="2018-09-12 9 36 36" src="https://user-images.githubusercontent.com/16275188/45425397-339c3f80-b6d4-11e8-8136-e06821f54d04.png">
