### ISSUE TITLE
토탈 근무시간 0으로 나오는 문제

### ISSUE THREAD

**Issue by changmink** [mash-up-kr/Checkmate-ios#14]
## 상황
토탈 근무시간 0으로 뜨는 문제
<img width="273" alt="2018-09-25 8 44 28" src="https://user-images.githubusercontent.com/7522327/46012346-ea9cb000-c103-11e8-8ff1-b35895e95a75.png">

## 원인
GET /user/{userId}/work/{workId}/main에서
```
{
   "base_day": 31,
   "total_day": 25,
   "total_money": 691200,
   "total_hour": 72,
   "hourly_wage": 8000
}
```
가 아니라
```
{
    "base_day":31,
    "total_day":1,
    "total_money":90360
}
```
로 나와서 그렇다. 현재 서버에 확인함

**Comment by changmink** [comment]
서버에서 AWS 반영 안한걸로 확인

**Comment by jo-bata** [comment]
EC2에 수정사항 반영 완료

**Comment by changmink** [comment]
시간 뜨는거 확인
<img width="250" alt="2018-09-25 10 10 35" src="https://user-images.githubusercontent.com/7522327/46016592-289fd100-c110-11e8-9562-1676f9b47974.png">
