### ISSUE TITLE
월급날이 되면 초기화가 안되는 문제

### ISSUE THREAD

**Issue by changmink** [mash-up-kr/Checkmate-ios#16]
<img width="285" alt="2018-09-26 3 10 31" src="https://user-images.githubusercontent.com/7522327/46060518-a0b4d800-c19e-11e8-973e-ede515a67a00.png">

**Comment by jo-bata** [comment]
월급날을 기준으로 현재일자가 더 작거나 같을 경우에는 올바르게 계산되는데 현재 일자가 더 클 경우에 계산 문제가 발생하는 것 같습니다.

**Comment by jo-bata** [comment]
### response
![image](https://user-images.githubusercontent.com/36880294/46063419-bb3f7f00-c1a7-11e8-9dba-4a74e21811ce.png)
- 수정완료했습니다 !

**Comment by changmink** [comment]
정상 동작 확인
<img width="305" alt="2018-09-26 4 25 04" src="https://user-images.githubusercontent.com/7522327/46063828-d65ebe80-c1a8-11e8-9213-654aa6e11e4d.png">
