### ISSUE TITLE
홈화면 서버와 통신해서 정보 뿌리기

### ISSUE THREAD

**Issue by Noverish** [mash-up-kr/Checkmate-ios#9]

**Comment by changmin-dev** [comment]
너무 막짜는거 같아서 오늘은 일단 접고 다시 생각해봐야겠음

**Comment by changmink** [comment]
## 변하는 값들

### 메인 화면

- [x] 1.현재까지 번돈: 이번달에 일한날짜 * (시급 * 일일 근무시간)
- [x] 2. 월급날까지 남은날
- [x] 3. 오늘이 며칠인지
- [x] 4. 이번달의 총 일수에서 오늘의 비율
- [x] 5. 알바 장소
- [x] 6. 오늘 날짜
- [x] 7. 시급
- [x] 8. 누적 근무 시간
- [x] 9. 근무중인지 여부

### 사이드바

- [x] 10. 현재 알바
- [x] 11. 알바리스트

## 값들의 관계
알바리스트(11)는 서버에서 제공 받는다. 실패하면 처리가 필요
현재 알바(10)는 리스트에서 선택된 알바이다. 알바가 없다면(리스트의 길이가 0이면) 처리가 필요
현재까지 번돈(1)은 서버가 계산해서 제공한다.(api), 8번도 api이용
오늘 날짜(6)를 알면 2,3,4계산가능. 2번은 문제가 있는게 월급날은 바뀌게 되어 있음 때문에 api사용
알바 장소(5)는 사이드바에서 선택한다. 선택되지 않으면 가장 처음알바. 알바가 하나도 없으면? 디폴트 정보가 있어야한다. 알바 장소(5)를 알면 7을 얻을 수 있다.
근무여부는 버튼으로 on/off한다.

**Comment by changmin-dev** [comment]
현재까지 번돈(1)은 서버가 계산해서 제공한다.
오늘 날짜(6)를 알면 2,3,4계산가능
알바 장소(5)는 사이드바에서 선택한다. 선택되지 않으면 가장 처음알바. 알바가 하나도 없으면? 디폴트 정보가 있어야한다. 알바 장소(5)를 알면

**Comment by changmink** [comment]
초기 총 월급에 문제 있었지만 해결 하지만 날짜 처리(남은 날짜)에 문제 있어서 수정필요. 그래프도 바뀌어야 한다.

api에 있는 내용에 따르면 그래프 비율은 다음과 같다.
`그래프 비율 = ( base_day-total_day) / base_day`
